# Generated by Django 4.2.2 on 2023-07-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='avatar',
        ),
    ]
