# Generated by Django 4.2.2 on 2023-07-12 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_info_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='attached_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 22, 8, 17, 467212, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='avatar',
            field=models.ImageField(default='user_avatars/default/default_avatar.jpg', upload_to='user_avatars/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='last_online_time',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 22, 8, 17, 467475, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
